# https://honk.sigxcpu.org/projects/git-buildpackage/manual-html

[DEFAULT]
upstream-tag = %(version)s
debian-tag = debian/%(version)s
upstream-branch = upstream
debian-branch = main
pristine-tar = True
